import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "getting started",
  description: "Generated by create next app - Jitendriya Meher",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAZ1nQg4eskTraVio4yO5yNCdty-MQo6p7qw&usqp=CAU" />
      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
